# Generated by Django 4.1.3 on 2022-12-25 09:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_request_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='tell_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
