# Generated by Django 4.1.3 on 2022-12-25 09:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_request_tell_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='tell_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=30, region=None),
        ),
    ]
