# Generated by Django 4.1.3 on 2023-05-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_regexp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manual',
            name='view',
        ),
    ]
