# Generated by Django 4.1.3 on 2023-05-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_regexp', '0003_exercise_alter_manual_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='answer',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='example',
            field=models.CharField(default='fgfg', max_length=200),
            preserve_default=False,
        ),
    ]
