# Generated by Django 4.1.3 on 2024-02-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_regexp', '0004_exercise_answer_exercise_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
