# Generated by Django 4.1.3 on 2023-04-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
