# Generated by Django 4.1.3 on 2023-04-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('view', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=200)),
                ('symbol', models.CharField(max_length=10)),
                ('example', models.TextField(max_length=200)),
            ],
        ),
    ]
