# Generated by Django 4.1.3 on 2023-05-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_regexp', '0002_remove_manual_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('solution', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='manual',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
